spring.application.name: spring-data-service

server.port: 8081

management.server.port: 8082

spring.data.rest.basePath: /api

# Local Cassandra defaults
spring:
  data:
    cassandra:
      keyspace-name: betterbotz
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
      schema-action: create-if-not-exists

---
spring.profiles: docker
spring:
  data:
    cassandra:
      port: 9042
      contact-points: host.docker.internal
      local-datacenter: dc1
      schema-action: create-if-not-exists